# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterTracer
                                 A QGIS plugin
 This plugin traces the underlying raster map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-09
        copyright            : (C) 2019 by Mikhail Kondratyev
        email                : mkondratyev85@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterTracer class from file RasterTracer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_tracer import RasterTracer
    return RasterTracer(iface)
